[package]
name = "gosh-dense-balanced-tree"
version = "0.1.0"
edition = "2021"
description = "Dense balanced Merkle tree proof verification circuit (GOSH crypto library)"

[dependencies]
halo2-base = { git = "https://github.com/gosh-sh/halo2-lib-zkevm-sha256-and-bls12-381", branch = "bump-halo2-lib-v0.4.1", default-features = false, features = ["halo2-axiom"] }
pse-poseidon = { git = "https://github.com/axiom-crypto/pse-poseidon.git" }

[dev-dependencies]
halo2-base = { git = "https://github.com/gosh-sh/halo2-lib-zkevm-sha256-and-bls12-381", branch = "bump-halo2-lib-v0.4.1", default-features = false, features = ["halo2-axiom", "test-utils"] }
dense-balanced-tree = { git = "https://github.com/gosh-sh/dense-balanced-tree" }
hex = "0.4"
rand = "0.8"
